const initialServices = [
  {
    icon: 'Globe',
    slug: 'web-development',
    heroImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1000&h=750&q=70',
    title: 'Web Development',
    desc: 'Build secure, responsive, and high-performing websites, web applications, SaaS platforms, customer portals, and internal dashboards. We create flexible architectures that support new users, features, and integrations as your business grows.',
    color: 'text-blue-600 bg-blue-50',
    gradient: 'from-blue-500 to-cyan-600',
    longDesc: 'We design and develop high-performance websites and web apps that look sharp, load fast, and convert. From marketing sites to complex platforms, every build is responsive, SEO-ready and easy to maintain.',
    features: ['Responsive & mobile-first layouts', 'SEO-friendly architecture', 'CMS & headless options', 'Performance optimization', 'Secure authentication & APIs', 'Ongoing support & iterations'],
    tech: ['React', 'Next.js', 'Node.js', 'TypeScript', 'Tailwind'],
    outcomes: ['Faster page loads', 'Higher conversion rates', 'Easier content updates'],
  },
  {
    icon: 'Smartphone',
    slug: 'mobile-app-development',
    heroImage: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=1000&h=750&q=70',
    title: 'Mobile App Development',
    desc: 'Turn your product concept into a smooth mobile experience for iOS and Android. Our team develops native and cross-platform apps with intuitive navigation, stable performance, secure data handling, and scalable back-end systems.',
    color: 'text-emerald-600 bg-emerald-50',
    gradient: 'from-emerald-500 to-teal-600',
    longDesc: 'Native-feeling mobile apps for iOS and Android from a single codebase. We focus on smooth UX, offline support, and store-ready quality so you launch with confidence.',
    features: [
      'iOS App Development',
      'Android App Development',
      'React Native apps',
      'Flutter App Development',
      'Ionic App Development',
      'IoT-connected mobile experiences',
      'App Store & Play Store launch',
      'Ongoing maintenance & updates',
    ],
    tech: ['Flutter', 'React Native', 'Swift', 'Kotlin', 'Firebase'],
    outcomes: ['One codebase, two platforms', 'Faster time-to-store', 'Consistent UX'],
  },
  {
    icon: 'BrainCircuit',
    slug: 'ai-development',
    heroImage: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1000&h=750&q=70',
    title: 'AI Product Development',
    desc: 'Use AI to automate repetitive work, improve customer experiences, analyze data, and support faster decisions. We develop practical AI applications, intelligent assistants, recommendation systems, and workflow automation tools connected to your business processes.',
    color: 'text-primary-600 bg-primary-50',
    gradient: 'from-violet-500 to-primary-600',
    longDesc: 'We integrate practical AI into real workflows — chatbots, document intelligence, recommendations, and process automation that save hours every week without overengineering.',
    features: ['Custom GPT / LLM apps', 'Process automation', 'Document & data extraction', 'Recommendation systems', 'Internal AI copilots', 'Secure private deployments'],
    tech: ['OpenAI', 'Python', 'LangChain', 'Vector DBs', 'AWS'],
    outcomes: ['Less manual work', 'Faster decisions', 'New product capabilities'],
  },
  {
    icon: 'Cloud',
    slug: 'cloud-solutions',
    heroImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1000&h=750&q=70',
    title: 'Cloud and DevOps',
    desc: 'Create a reliable technical foundation for your product through cloud architecture, automated deployment, monitoring, security, and performance optimization. Our DevOps approach helps teams release updates faster while reducing downtime and infrastructure risks.',
    color: 'text-sky-600 bg-sky-50',
    gradient: 'from-sky-500 to-blue-600',
    longDesc: 'Infrastructure that grows with you. We set up cloud environments, CI/CD, monitoring and cost controls so releases are boring — in the best way.',
    features: ['AWS / Azure / GCP setup', 'CI/CD pipelines', 'Docker & Kubernetes', 'Monitoring & alerts', 'Cost optimization', 'Disaster recovery plans'],
    tech: ['AWS', 'Docker', 'Kubernetes', 'Terraform', 'GitHub Actions'],
    outcomes: ['Faster deployments', 'Higher uptime', 'Predictable costs'],
  },
  {
    icon: 'PenTool',
    slug: 'ui-ux-design',
    heroImage: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?auto=format&fit=crop&w=1000&h=750&q=70',
    title: 'UI/UX Design',
    desc: 'Give users a clear and enjoyable path through your product. Our UI/UX specialists turn research and business requirements into user flows, wireframes, interactive prototypes, accessible interfaces, and consistent design systems.',
    color: 'text-pink-500 bg-pink-50',
    gradient: 'from-pink-500 to-fuchsia-600',
    longDesc: 'Design that feels obvious to users and intentional to stakeholders. Research, wireframes, high-fidelity UI and design systems that developers can actually ship.',
    features: ['User research & flows', 'Wireframes & prototypes', 'High-fidelity UI kits', 'Design systems', 'Usability testing', 'Dev handoff support'],
    tech: ['Figma', 'FigJam', 'Principle', 'Storybook'],
    outcomes: ['Clearer product direction', 'Higher engagement', 'Smoother build process'],
  },
  {
    icon: 'ShoppingCart',
    slug: 'ecommerce-solutions',
    heroImage: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1000&h=750&q=70',
    title: 'E-Commerce Development',
    desc: 'Launch or improve an online store, marketplace, or subscription platform built around easier product discovery and checkout. We support secure payments, inventory systems, third-party integrations, mobile optimization, and simple store management.',
    color: 'text-orange-500 bg-orange-50',
    gradient: 'from-orange-500 to-amber-600',
    longDesc: 'Stores built to sell — fast product pages, smooth checkout, smart upsells and integrations with the tools you already use for inventory, shipping and marketing.',
    features: ['Custom storefronts', 'Checkout optimization', 'Payment gateways', 'Inventory sync', 'Upsells & subscriptions', 'Analytics dashboards'],
    tech: ['Shopify', 'WooCommerce', 'Next.js', 'Stripe', 'Laravel'],
    outcomes: ['Higher AOV', 'Lower cart abandonment', 'Easier operations'],
  },
  {
    icon: 'ServerCog',
    slug: 'laravel-development',
    heroImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1000&h=750&q=70',
    title: 'Laravel Development',
    desc: 'Powerful and scalable web applications using the Laravel PHP framework for complex business logic.',
    color: 'text-red-500 bg-red-50',
    gradient: 'from-red-500 to-rose-600',
    longDesc: 'Laravel is our go-to for robust backends and admin-heavy products. We build clean, tested APIs and dashboards that scale with your business logic without becoming a maintenance burden.',
    features: ['Custom admin panels', 'REST & GraphQL APIs', 'Queue jobs & scheduling', 'Multi-tenant apps', 'Payment integrations', 'Role-based access control'],
    tech: ['Laravel', 'PHP', 'MySQL', 'Redis', 'Vue'],
    outcomes: ['Reliable backends', 'Faster feature delivery', 'Lower long-term cost'],
  },
  {
    icon: 'Tablet',
    slug: 'ios-development',
    heroImage: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=1000&h=750&q=70',
    title: 'iOS Development',
    desc: 'Native iPhone and iPad apps built with Swift and SwiftUI — fast, polished, and App Store ready.',
    color: 'text-slate-700 bg-slate-100',
    gradient: 'from-slate-700 to-sky-500',
    longDesc: 'We design and build native iOS applications that feel at home on iPhone and iPad. From SwiftUI interfaces to solid architecture, App Store submission and ongoing updates — your product gets the performance and polish Apple users expect.',
    features: [
      'Native Swift & SwiftUI apps',
      'UIKit when needed for complex UI',
      'App Store submission & review support',
      'Push notifications & deep linking',
      'In-app purchases & subscriptions',
      'iPad and multi-device layouts',
      'Core Data & CloudKit sync',
      'CI builds and TestFlight delivery',
    ],
    tech: ['Swift', 'SwiftUI', 'UIKit', 'Xcode', 'Firebase', 'Combine'],
    outcomes: [
      'Buttery-smooth native performance',
      'Faster App Store approval cycles',
      'Maintainable, modern Swift codebase',
    ],
  },
  {
    icon: 'AppWindow',
    slug: 'android-development',
    heroImage: 'https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?auto=format&fit=crop&w=1000&h=750&q=70',
    title: 'Android Development',
    desc: 'Native Android apps with Kotlin and Jetpack — Material Design, Play Store ready, built for performance.',
    color: 'text-emerald-600 bg-emerald-50',
    gradient: 'from-emerald-500 to-teal-600',
    longDesc: 'We build native Android applications that feel fast and familiar on phones and tablets. Kotlin, Jetpack libraries, Material Design, and a clear path to Google Play — so your product reaches billions of devices with the quality users expect.',
    features: [
      'Native Kotlin & Jetpack Compose',
      'Material Design 3 interfaces',
      'Google Play submission support',
      'Push notifications & deep links',
      'In-app billing & subscriptions',
      'Tablet and foldable-friendly layouts',
      'Room, WorkManager & modern architecture',
      'CI builds and internal testing tracks',
    ],
    tech: ['Kotlin', 'Jetpack Compose', 'Android Studio', 'Firebase', 'Material 3'],
    outcomes: [
      'Smooth native Android performance',
      'Faster Play Console releases',
      'Clean, maintainable Kotlin codebase',
    ],
  },
  {
    icon: 'Boxes',
    slug: 'devops',
    heroImage: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?auto=format&fit=crop&w=1000&h=750&q=70',
    title: 'DevOps',
    desc: 'CI/CD, infrastructure as code, and reliable cloud operations that keep releases fast and systems stable.',
    color: 'text-cyan-600 bg-cyan-50',
    gradient: 'from-cyan-500 to-primary-600',
    longDesc: 'We help teams ship faster with less drama. From CI/CD pipelines and infrastructure as code to monitoring, security, and cloud cost control — Cubixsol builds the operational backbone so your product stays reliable as you grow.',
    features: [
      'CI/CD pipelines (GitHub Actions, GitLab CI, Jenkins)',
      'Infrastructure as Code (Terraform, CloudFormation)',
      'Containerization with Docker & Kubernetes',
      'Cloud setup on AWS, GCP, and Azure',
      'Monitoring, logging & alerting',
      'Security scanning & secrets management',
      'Automated testing in the pipeline',
      'Release strategies (blue/green, canary)',
    ],
    tech: ['Docker', 'Kubernetes', 'Terraform', 'AWS', 'GitHub Actions', 'Prometheus'],
    outcomes: [
      'Faster, safer releases',
      'Fewer production incidents',
      'Clearer visibility into system health',
    ],
  },
  {
    icon: 'TrendingUp',
    slug: 'digital-marketing',
    heroImage: 'https://images.unsplash.com/photo-1432888622747-4eb9a8f2c1c9?auto=format&fit=crop&w=1000&h=750&q=70',
    title: 'Digital Marketing Services',
    heroSubtitle: 'Turn online attention into measurable business growth.',
    desc: 'Cubixsol provides **digital marketing services** to attract qualified traffic, generate stronger leads, and improve customer acquisition across search, paid media, social platforms, and email.',
    ctaPrimaryText: 'Get a Free Marketing Audit',
    ctaSecondaryText: 'Talk to Our Marketing Team',
    additionalParagraph: 'We combine strategy, execution, and performance analysis in one coordinated service. Our **digital marketing agency services** cover SEO, PPC, social media, content, email, and local search, while our **digital marketing consulting services** give internal teams a clear plan for improving campaigns, budgets, and channel performance.',
    color: 'text-amber-600 bg-amber-50',
    gradient: 'from-amber-500 to-yellow-600',
    longDesc: 'Cubixsol provides **digital marketing services** to attract qualified traffic, generate stronger leads, and improve customer acquisition across search, paid media, social platforms, and email.',
    features: [
      'Search Engine Optimization (SEO)',
      'Social Media Marketing',
      'Email Marketing',
      'PPC Advertising',
      'Content Writing',
      'Analytics & Reporting',
    ],
    businessTypesTitle: 'Digital Marketing for Your Business',
    businessTypesIntro: 'Different business models need different channel priorities, sales messages, and measures of success. Our team builds the strategy around how your company attracts, converts, and retains customers.',
    businessTypesItems: [
      {
        title: 'Small Businesses',
        desc: 'Our **digital marketing services for small businesses** prioritize the channels most likely to generate near-term value. Focused campaigns, practical budgets, and clear reporting help smaller teams compete without paying for activity they do not need.',
      },
      {
        title: 'B2B Companies',
        desc: 'Our **B2B digital marketing services** connect search, content, paid media, and lead nurturing with longer sales cycles. Campaigns target relevant decision-makers and support the journey from initial research to sales conversation.',
      },
      {
        title: 'Financial Services',
        desc: '**Digital marketing for financial services** requires credibility, careful messaging, and close attention to platform and industry requirements. We create campaigns that explain complex offers clearly while supporting trust, lead quality, and responsible customer acquisition.',
      },
      {
        title: 'E-Commerce Brands',
        desc: 'Our **ecommerce digital marketing services** combine product-focused SEO, paid acquisition, remarketing, email automation, and conversion insights. The goal is to attract purchase-ready shoppers, recover missed sales, and increase customer value over time.',
      },
      {
        title: 'Home Service Providers',
        desc: 'Our approach to **home services digital marketing** focuses on local intent, service-area visibility, calls, quote requests, and booked jobs. SEO, paid search, and location-focused landing pages help customers find the right service when demand is highest.',
      },
    ],
    pricingSectionTitle: 'Affordable, Transparent Pricing',
    pricingSectionText: '**Affordable digital marketing services** should reduce unnecessary spending without cutting the work that drives performance. Cubixsol recommends channels and deliverables according to your goals, competitive environment, and available budget, then explains where the investment goes. Agencies can also use our **white-label digital marketing services** to expand delivery capacity while keeping client relationships and branding under their control.',
    tech: ['GA4', 'Search Console', 'Meta Ads', 'Google Ads', 'HubSpot'],
    outcomes: ['More qualified traffic', 'Lower cost per lead', 'Clear attribution'],
    seo: {
      metaTitle: 'Digital Marketing Services | Cubixsol',
      metaDescription: 'Cubixsol provides digital marketing services to attract qualified traffic, generate stronger leads, and improve customer acquisition across search, paid media, social platforms, and email.',
    },
  },
  {
    icon: 'Webhook',
    slug: 'api-development',
    heroImage: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1000&h=750&q=70',
    title: 'API Development & Integration',
    desc: 'Secure APIs, PMS connections, and payment gateways that connect your product to the tools your business runs on.',
    color: 'text-indigo-600 bg-indigo-50',
    gradient: 'from-indigo-500 to-violet-600',
    longDesc: 'We design and integrate APIs that keep systems in sync — from custom REST and GraphQL services to property management systems and payment providers. Reliable, documented, and built for the load your product will see in production.',
    features: [
      'Custom REST & GraphQL API design',
      'API Integration with third-party platforms',
      'PMS Integration (property & booking systems)',
      'Payment Gateways (Stripe, PayPal, local providers)',
      'Webhooks, events & real-time sync',
      'Auth, rate limits & API security',
      'Documentation & developer portals',
      'Monitoring, retries & error handling',
    ],
    tech: ['Node.js', 'Python', 'REST', 'GraphQL', 'Stripe', 'OAuth'],
    outcomes: [
      'Systems that stay in sync',
      'Faster checkout and bookings',
      'Fewer manual handoffs between tools',
    ],
  },
  {
    icon: 'LayoutTemplate',
    slug: 'cms-development',
    heroImage: 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&w=1000&h=750&q=70',
    title: 'CMS Development',
    desc: 'WordPress, Shopify, Magento, and more — CMS builds that are fast to manage and ready to grow.',
    color: 'text-violet-600 bg-violet-50',
    gradient: 'from-violet-500 to-purple-600',
    longDesc: 'We build and customize content platforms so your team can publish, sell, and iterate without fighting the CMS. From WordPress and Shopify to Magento, BigCommerce, Joomla, and OpenCart — clean themes, solid plugins, and performance that holds up.',
    features: [
      'Magento Development',
      'Shopify Development',
      'WordPress Development',
      'BigCommerce Development',
      'Joomla Development',
      'OpenCart Development',
      'Theme & plugin customization',
      'Migrations and performance tuning',
    ],
    tech: ['WordPress', 'Shopify', 'Magento', 'WooCommerce', 'PHP', 'Liquid'],
    outcomes: [
      'Easier content and catalog updates',
      'Faster storefront performance',
      'Cleaner admin workflows',
    ],
  },
  {
    icon: 'FileCode',
    slug: 'php-development',
    heroImage: 'https://images.unsplash.com/photo-1599507593499-a69270d22dc9?auto=format&fit=crop&w=1000&h=750&q=70',
    title: 'PHP Development',
    desc: 'Laravel, CodeIgniter, CakePHP, and ongoing PHP maintenance for reliable backend systems.',
    color: 'text-purple-600 bg-purple-50',
    gradient: 'from-purple-500 to-indigo-600',
    longDesc: 'PHP still powers a huge share of the web. We build and maintain Laravel, CodeIgniter, and CakePHP applications with modern practices — secure, testable, and ready for the next phase of your product.',
    features: [
      'CakePHP Development',
      'Laravel Development',
      'CodeIgniter Development',
      'PHP Maintenance and Support',
      'Legacy modernization',
      'API backends in PHP',
      'Security hardening & upgrades',
      'Performance and caching',
    ],
    tech: ['PHP', 'Laravel', 'CodeIgniter', 'CakePHP', 'MySQL', 'Redis'],
    outcomes: [
      'Stable, maintainable backends',
      'Safer upgrades from legacy code',
      'Faster feature delivery on PHP stacks',
    ],
  },
  {
    icon: 'Database',
    slug: 'data-migration-services',
    heroImage: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1000&h=750&q=70',
    title: 'Data Migration',
    desc: 'Software, website, application, SEO, and database migrations with minimal downtime and clear validation.',
    color: 'text-sky-600 bg-sky-50',
    gradient: 'from-sky-500 to-blue-600',
    longDesc: 'Moving systems is risky when it is rushed. We plan and execute software, website, application, SEO, and database migrations with cutover plans, validation, and rollback options so your business keeps running.',
    features: [
      'Software Migration',
      'Website Migration',
      'Application Migration',
      'SEO Migration',
      'Database Migration',
      'Content and media transfer',
      'URL mapping & redirects',
      'Post-migration hypercare',
    ],
    tech: ['SQL', 'ETL', 'AWS', 'Scripts', 'CDN', 'Search Console'],
    outcomes: [
      'Lower migration risk',
      'Preserved SEO equity',
      'Verified data after cutover',
    ],
  },
  {
    icon: 'Palette',
    slug: 'graphic-design',
    heroImage: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=1000&h=750&q=70',
    title: 'Graphic Designing',
    desc: 'UI/UX, web and mobile design, social creatives, branding, and illustration that support real products.',
    color: 'text-pink-600 bg-pink-50',
    gradient: 'from-pink-500 to-rose-600',
    longDesc: 'Design that ships with your product — interfaces, marketing visuals, and brand systems. We cover UI/UX, web and mobile layouts, social media design, branding and identity, and illustration support when campaigns need a distinctive look.',
    features: [
      'UI/UX Designing',
      'Web design',
      'Mobile app design',
      'Social Media Design',
      'Branding and Identity Design',
      '3D Illustrations',
      'Design systems & components',
      'Handoff-ready production files',
    ],
    tech: ['Figma', 'Adobe Suite', 'Framer', 'Principle', 'Illustrator'],
    outcomes: [
      'Clearer product interfaces',
      'Stronger brand consistency',
      'Faster design-to-dev handoff',
    ],
  },
];

const initialSolutions = [
  { title: 'Data Engineering', slug: 'data-engineering', category: 'Data Solutions', group: 'Data Solutions', desc: 'Pipelines, warehouses, and reliable data platforms.' },
  { title: 'BI & Data Analytics', slug: 'bi-data-analytics', category: 'Data Solutions', group: 'Data Solutions', desc: 'Dashboards and insights that drive decisions.' },
  { title: 'Data Governance and Security', slug: 'data-governance-security', category: 'Data Solutions', group: 'Data Solutions', desc: 'Policies, access control, and data quality.' },
  { title: 'Data Migration', slug: 'data-migration', category: 'Data Solutions', group: 'Data Solutions', desc: 'Safe moves between systems with minimal downtime.' },
  { title: 'Data Scraping', slug: 'data-scraping', category: 'Data Solutions', group: 'Data Solutions', desc: 'Ethical collection and structuring of web data.' },
  { title: 'Oracle AI Data Platform', slug: 'oracle-aidp', category: 'Data Solutions', group: 'Data Solutions', desc: 'AIDP assessment, migration, and Oracle data platform engineering.' },

  { title: 'Agentic AI', slug: 'agentic-ai', category: 'Artificial Intelligence', group: 'Artificial Intelligence', desc: 'Autonomous agents that plan and execute workflows.' },
  { title: 'Deep Learning', slug: 'deep-learning', category: 'Artificial Intelligence', group: 'Artificial Intelligence', desc: 'Models for vision, speech, and complex prediction.' },
  { title: 'Generative AI', slug: 'generative-ai', category: 'Artificial Intelligence', group: 'Artificial Intelligence', desc: 'LLMs and generative tools tailored to your domain.' },
  { title: 'Predictive Analysis', slug: 'predictive-analysis', category: 'Artificial Intelligence', group: 'Artificial Intelligence', desc: 'Forecasting demand, risk, and customer behavior.' },
  { title: 'Sentiment Analysis', slug: 'sentiment-analysis', category: 'Artificial Intelligence', group: 'Artificial Intelligence', desc: 'Understand customer voice at scale.' },
  { title: 'Data Science', slug: 'data-science', category: 'Artificial Intelligence', group: 'Artificial Intelligence', desc: 'Experimentation, modeling, and MLOps.' },
  { title: 'AI Consulting', slug: 'ai-consulting', category: 'Artificial Intelligence', group: 'Artificial Intelligence', desc: 'Strategy, readiness, and roadmap for AI adoption.' },

  { title: 'AI Chatbots & Customer Support', slug: 'ai-chatbots-support', category: 'E-Commerce', group: 'E-Commerce', desc: 'Conversational support that resolves and escalates smartly.' },
  { title: 'eCommerce Development', slug: 'ecommerce-development', category: 'E-Commerce', group: 'E-Commerce', desc: 'Storefronts built to convert and scale.' },
  { title: 'Voice Commerce', slug: 'voice-commerce', category: 'E-Commerce', group: 'E-Commerce', desc: 'Voice-driven shopping and ordering experiences.' },
  { title: 'Customer Segmentation', slug: 'customer-segmentation', category: 'E-Commerce', group: 'E-Commerce', desc: 'Smarter audiences for campaigns and personalization.' },

  { title: 'Image to Text', slug: 'image-to-text', category: 'Accessibility Tools', group: 'Accessibility Tools', desc: 'Free OCR — extract text from images in 200+ languages.', externalUrl: 'https://imagetotext.best/' },
  { title: 'Reescrever Texto', slug: 'reescrever-texto', category: 'Accessibility Tools', group: 'Accessibility Tools', desc: 'Rewrite and improve text for clarity and style.', externalUrl: 'https://reescrevertexto.io/' },
  { title: 'JPGA PDF', slug: 'jpg-a-pdf', category: 'Accessibility Tools', group: 'Accessibility Tools', desc: 'Convert JPG images to PDF quickly online.', externalUrl: 'https://jpgapdf.io/' },
  { title: 'JPG to PDF', slug: 'jpg-to-pdf', category: 'Accessibility Tools', group: 'Accessibility Tools', desc: 'Turn JPG files into polished PDF documents.', externalUrl: 'https://jpg2pdf.io/' },
  { title: 'AI SEO Auditor', slug: 'ai-seo-auditor', category: 'Accessibility Tools', group: 'Accessibility Tools', desc: 'AI-powered site audits for SEO, content, and technical health.', externalUrl: '/tools/ai-seo-auditor' },
];

const initialProducts = [
  {
    slug: 'workstream',
    name: 'Workstream',
    title: 'The All-in-One Management Tool Built for Enterprise Needs',
    tagline: 'Simplify workflows by 50%, boost communication, and empower employees — one platform.',
    desc: 'Streamline team operations and approvals with customizable workflows and real-time tracking.',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&h=750&q=80',
    accent: 'from-blue-100 to-sky-50',
    heroTheme: 'navy',
    category: 'Enterprise',
  },
  {
    slug: 'hirestream',
    name: 'Hirestream',
    title: 'Recruitment Automation Tool',
    tagline: 'Pipelines that move candidates forward — not spreadsheets that stall them.',
    desc: 'Automate hiring pipelines, reduce manual effort, and make smarter recruitment decisions.',
    image: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1200&h=750&q=80',
    accent: 'from-cyan-100 to-teal-50',
    heroTheme: 'teal',
    category: 'HR Tech',
  },
  {
    slug: 'fix-alert',
    name: 'FixAlert',
    title: 'Real-time Maintenance Reporting',
    tagline: 'Report issues. Dispatch teams. Close the loop — from any site.',
    desc: 'Instantly report and resolve infrastructure issues with a centralized, mobile-friendly system.',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&h=750&q=80',
    accent: 'from-amber-100 to-orange-50',
    heroTheme: 'coral',
    category: 'Operations',
  },
];

const initialIndustries = [
  {
    slug: 'education',
    title: 'Education',
    icon: 'GraduationCap',
    short: 'Learning platforms, school systems, and engagement tools.',
    desc: 'Cubixsol designs and builds digital products for schools, universities, and EdTech companies — from learner engagement and LMS features to parent communication and multi-institution content delivery.',
    points: [
      'Learning platforms & LMS modules',
      'School & parent communication apps',
      'Content delivery at scale',
      'Progress & completion analytics',
      'Assessment and quiz engines',
      'Role-based portals for staff and students',
    ],
  },
  {
    slug: 'healthcare',
    title: 'Healthcare & Life Sciences',
    icon: 'HeartPulse',
    short: 'Patient portals, clinical tools, and HIPAA-minded systems.',
    desc: 'Secure digital solutions for healthcare providers, clinics, and health-tech startups — telemedicine, booking, EHR-adjacent tools, and patient engagement built for reliability and privacy.',
    points: [
      'Telemedicine & remote consultations',
      'Patient & provider portals',
      'Appointment & intake automation',
      'Secure messaging & notifications',
    ],
  },
  {
    slug: 'ecommerce',
    title: 'Retail & E-Commerce',
    icon: 'ShoppingBag',
    short: 'Storefronts, checkout optimization, and omnichannel sales.',
    desc: 'High-converting online stores, multi-vendor marketplaces, and custom checkout flows tailored for brands looking to scale online revenue.',
    points: ['Custom storefront builds', 'Checkout optimization', 'Inventory synchronization', 'Payment gateway integrations'],
  },
  {
    slug: 'finance',
    title: 'Finance & Banking',
    icon: 'Landmark',
    short: 'Fintech platforms, payment flows, and data compliance.',
    desc: 'Digital banking interfaces, wallet apps, and loan automation software built with top-tier security standards.',
    points: ['Secure payment gateways', 'Fintech dashboards', 'KYC & compliance workflows', 'Real-time financial analytics'],
  },
  {
    slug: 'saas',
    title: 'SaaS',
    icon: 'Cloud',
    short: 'Multi-tenant products built to onboard, retain, and scale.',
    desc: 'We partner with SaaS teams on product engineering — from MVP to scale — with solid tenancy, billing hooks, admin, and customer-facing UX.',
    points: ['Multi-tenant architecture', 'Onboarding & activation', 'Billing integrations', 'Admin & analytics'],
  },
  {
    slug: 'logistics',
    title: 'Logistics',
    icon: 'Truck',
    short: 'Tracking, dispatch, and operations visibility on the move.',
    desc: 'Logistics software for dispatch, tracking, and partner coordination — mobile-friendly field tools and control-tower dashboards.',
    points: ['Dispatch & routing support', 'Shipment tracking UX', 'Partner portals', 'Ops dashboards'],
  },
  {
    slug: 'travel',
    title: 'Travel & Hospitality',
    icon: 'Plane',
    short: 'Booking journeys and guest experiences that convert.',
    desc: 'Booking flows, supplier integrations, and guest apps for travel and hospitality brands that need reliability at peak demand.',
    points: ['Booking & availability', 'Supplier APIs', 'Guest mobile experiences', 'Loyalty hooks'],
  },
  {
    slug: 'technology',
    title: 'Technology',
    icon: 'Cpu',
    short: 'Platforms, developer tools, and internal tech products.',
    desc: 'For technology companies building platforms or internal tools, we embed as an engineering partner — architecture, delivery, and UI that matches product standards.',
    points: ['Platform features', 'Internal tools', 'API products', 'Design systems'],
  },
];

module.exports = {
  initialServices,
  initialSolutions,
  initialProducts,
  initialIndustries,
};
